version: '3.1'

services:
  db:
    image: postgres:11.6-alpine
    restart: always
    container_name: db-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 3309:5432
